### ISSUE TITLE
only one host

### ISSUE THREAD

**Issue by quickstreamingmedia** [opentok/broadcast-sample-app#11]
only one host and change output layout

**Comment by quickstreamingmedia** [comment]
Also want to know 1-many with multiple rooms

**Comment by msach22** [comment]
@quickstreamingmedia Hi, could you please elaborate on what you mean by "only one host and change output layout" and "1-many with multiple rooms"?

**Comment by quickstreamingmedia** [comment]
imagine like youtube live

**Comment by quickstreamingmedia** [comment]
1 host and multiple viewers

**Comment by msach22** [comment]
@quickstreamingmedia This specific broadcast sample app allows you to have a minimum of 1 guest along with 1 host so you can reach approximately a 150 viewers. You can reach a large audience using HLS or RTMP, where you can feed the video stream to an RTMP provider like YouTube or Facebook. For more info, please visit: https://tokbox.com/developer/guides/broadcast/live-streaming/
