### ISSUE TITLE
Apply SDK for production

### ISSUE THREAD

**Issue by Jagdeep-Sing** [opentok/broadcast-sample-app#12]
Hi, this is not a issue, i just want little help.
How can i apply SDK for generating the Session ID and Token values for this app?

if i test from given heroku urls, after starting broadcast when i view it from /viewer route from multiple desktops then i see multiple videos in /viewer page but it should be 1 only. i think it can solve if i apply sdk. am i right?

**Comment by adrice727** [comment]
Hi @Jagdeep-Sing.  It sounds like you only have a single `/host` tab with no `/guest` tabs?  If that's the case, you're correct, you should only be seeing a single video, which is the case when I run the app locally.  Can you walk me through the steps to reproduce this?

**Comment by Jagdeep-Sing** [comment]
Yes, I was using heroku instance, now i already setup the app on my server and tested there and i can see broadcast from multiple sources with single video.Now what i want is that on the same time many broadcasts can start. if i try now this with current app then new broadceast starts but with already running broadcast(i want to start broadcast for every broadcaster separetely). so i need to apply SDK for that? and also if this successfully created then how can i view specific broadcast because viewer route is one only. please clear my these doubts.

**Comment by Jagdeep-Sing** [comment]
@adrice727  ?

**Comment by adrice727** [comment]
@Jagdeep-Sing  I'm not sure I understand your use case.  You'd like to have an individual broadcast for each person publishing a stream, with each broadcast only containing a single stream?  That's not possible to do with a single session since each published stream would be included in the composed broadcast stream.  And, you can only have a single broadcast running for each session.  So, you would need to create separate sessions and start a broadcast for each session.

**Comment by Jagdeep-Sing** [comment]
@adrice727 Yes, I want like that because my app is in production and many broadcasters can start broadcast at same time as individual. can you please show me the path how can i create separate session and start broadcast for each session.

I am familier with opentok PHP SDK and used it in my previous apps in one to one and conference. 
But now, this case is different and its in node. node is not a problem, i just confused in sessions because i seen in code, sessions are already generating. Please provide some guide so that i can continue with my project.

**Comment by Jagdeep-Sing** [comment]
.
