### ISSUE TITLE
Latency and Low Video Fidelity

### ISSUE THREAD

**Issue by JamieCorkhill** [opentok/broadcast-sample-app#13]
Hello.

I just tried out this demo, and I must say, the results weren't promising. The guest's quality was rather bad for the viewer (with the guest being on the same machine), and having a host, guest, or viewer from a phone was even worse.

Is it possible that this demo, in particular, is not optimized and that's why I had low video quality? I ask because on the basis of the Heroku demo, I don't feel like I'm going to choose OpenTok for my use case.

**Comment by Vipin1988** [comment]
Hello,
I am trying to configure this demo on my localhost and at the time of run  node server.js showing error in terminal and i have saved tokens in config file also.

/var/www/html/broadcast-sample-app/services/opentok-api.js:6
const { apiKey, apiSecret } = require('../config');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/broadcast-sample-app/server.js:21:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by damanmokha** [comment]
@Vipin1988 can you please share your config file here for a more clear view.

**Comment by damanmokha** [comment]
@JamieCorkhill yes I am concerned about the same thing, any luck on it yet?

**Comment by MichaelJolley** [comment]
Hi @JamieCorkhill, you're correct that this demo is not optimized for a real-world use-case. It was created solely to show how to start/stop an HLS/RTMP broadcast using OpenTok. It has no considerations for features like Simulcast and no optimizations for mobile clients.

For best practices for multi-party video sessions, see [this blog post](https://www.nexmo.com/blog/2020/07/23/best-practices-for-multi-party-video-conferencing-with-the-vonage-video-api-dr).  You can also [customize the layouts of your broadcast](https://www.nexmo.com/blog/2020/09/22/dynamic-layouts-in-hls-rmtp-broadcasts-with-the-video-api-dr) using our built-in layouts or a custom layout of your choosing.
