### ISSUE TITLE
[Question] Do we need to call those broadcast apis in case of interactive broadcasting?

### ISSUE THREAD

**Issue by kumail-raza** [opentok/broadcast-sample-app#14]
In public/js/host.js, I like to know in-case of just interactive broadcasting do we require to call these apis? I don't want HLS/RTMP broadcasting, and here these apis I believe is to inform server to start/stop HLS broadcasting, and changing layout for HLS broadcasting? 

 ```js
 http.post('/broadcast/start')
 http.post('/broadcast/end')
 http.post('/broadcast/layout')
```

Urgent response on this will be appreciated! @MichaelJolley @adrice727

**Comment by kumail-raza** [comment]
??

**Comment by ggoldens** [comment]
@kumail-raza This sample app shows how to broadcast via WebRTC, HLS and RTMP. You don't need to implement HLS/RTMP API's if you don't need it.
