### ISSUE TITLE
Multiple Host Sessions

### ISSUE THREAD

**Issue by damanmokha** [opentok/broadcast-sample-app#16]
I was trying to have, multiple hosts sessions, with multiple users, eg. Host1's session can be joined by viewer1, viewer2 ... etc.
and Host2's session can be joined by viewer3, viewer4. But when I go to /host from when there is a session already started it opens the same session with the guest view.

**Comment by MichaelJolley** [comment]
Hi @damanmokha, this app is meant as a sample only of how to utilize the broadcast feature. It is not meant to scale to multiple sessions, but instead creates one session that is used by all endpoints (host/guest/viewer.) 

For your applications, you'll want to provide a backend that can support multiple sessions and generating credentials that are session specific.
