### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mango009** [opentok/broadcast-sample-app#17]
This repository doesn't seem to be maintained. The example
```
To try out the Broadcast Sample App, visit the following URLs:

Host: https://broadcast-sample.herokuapp.com/host
Guest: https://broadcast-sample.herokuapp.com/guest
Viewer: https://broadcast-sample.herokuapp.com/viewer
Broadcast Viewer: https://broadcast-sample.herokuapp.com/broadcast

```
Doesn't work at all. I reached out to Vonage support and they couldn't make it work either.

**Comment by ggoldens** [comment]
Thanks @mango009, it seems that there's a problem with flowplayer and the autoplay.

**Comment by MichaelJolley** [comment]
@mango009, could you try again? We've done some updates to the repo and it should work as intended. Gracias!
